### ISSUE TITLE
Remove Some Unnecessary Slash Commands

### ISSUE THREAD

**Issue by Gocnak** [momentum-mod/discord-bot#132]
These were old workarounds to problems that discord either didn't implement directly or when we were smaller and needed more help.

To remove:
```
/ban  - Discord has this built in, we should be adding more mods if we ever would need to use this anyways
/info  - Not really useful information from this? Might have only been used for membercount?
/membercount -  Discord now shows number of people that have a role in the roles page
/faq - We now use Carlbot for role approval
```

To combine:
```
/status and /clearstatus should just be /status with a "clear" and "set" command as the first parameter
/stats and /statstop could probably combine in a similar manner
/twitchban and /updatestreams could combine into a /streams "ban" and "update"
```

**Comment by tsa96** [comment]
We use `/info player` occasionally, I don't know any other ways to checking user account age. Seems find to keep IMO

**Comment by Gocnak** [comment]
Discord now has account age on profiles directly, just clicking on them:
![image](https://user-images.githubusercontent.com/5162166/192080551-63e04d15-4241-4d64-a112-eff4809184b6.png)

**Comment by BIRD311** [comment]
I think "/info user" is fine but "/info role" and "/info channel" can be removed. The account age doesn't show up on every profile (BLT, Shegetz, SlidyBat ...). Not sure if the bot command would still work or if it doesn't show because of privacy settings.
The roles page isn't visible for a lot of us so /membercount would still be useful unless you can share this page. I was thinking about moving membercount to "/info role" and just removing "/info channel".

about grouping things:
in the group "stats" we have 2 commads (user and channel) and in the group "statstop" we have 2 commands (users and channels)
A group can only have commands or groups but not both afaik so if I combine them I either get "/stats - user" and "/stats - topusers" or "/stats - foo - user" and "/stats - top - users". Not sure what call foo so I chose the first option. We could also combine /stats with /info.
Same problem for twitchban and updatestream.
